version: "3.9"

services:
  author:
    image: ghcr.io/mahedisabuj/aem-docker/aem-author:6.5.16
    ports:
      - "4502:4502"
      - "9511:9511"
    container_name: aem-author
    networks:
      - aem-docker

networks:
  aem-docker:
