version: "3.9"

services:
  dispatcher:
    image: ghcr.io/mahedisabuj/aem-docker/aem-dispatcher:1.0.0
    container_name: aem-dispatcher
    environment:
      - DISP_ID=docker
      ## Replace value with the Author IP and Port you are using:
      - AUTHOR_IP=aem-author
      - AUTHOR_PORT=4502
      - AUTHOR_DEFAULT_HOSTNAME=aem-author.com
      - AUTHOR_DOCROOT=/mnt/var/www/author
      ## Replace value with the Publisher IP and Port you are using:
      - PUBLISH_IP=aem-publish
      - PUBLISH_PORT=4503
      - PUBLISH_DEFAULT_HOSTNAME=aem-publish.com
      - PUBLISH_DOCROOT=/mnt/var/www/html
      ## Enable / Disable CRXDE access.  Production this should be disabled
      - CRX_FILTER=allow
      ## Allow dispatcher flush from any IP
      - DISPATCHER_FLUSH_FROM_ANYWHERE=allow
    tmpfs:
      - /tmp
    ports:
      - "80:80"
      - "443:443"