version: "3.9"

services:
  author:
    image: ghcr.io/mahedisabuj/aem-docker/aem-publish:6.5.16
    ports:
      - "4503:4503"
      - "9512:9512"
    container_name: aem-publish
    networks:
      - aem-docker

networks:
  aem-docker:
